import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// importing Radix UI styles
import '@radix-ui/themes/styles.css';
import { Theme } from '@radix-ui/themes';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Theme
          appearance="dark"
          accentColor="ruby"
          grayColor="gray"
          panelBackground="solid"
          scaling="100%"
          radius="medium"
        >
          {children}
        </Theme>
      </body>
    </html>
  );
}
